# .github/workflows/tester.yml
name: tester
on: [push, pull_request]

jobs:
  norminette_v3_job:
    runs-on: ubuntu-latest
    name: norminette v3
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3

  minishell_tester_job:
    runs-on: ubuntu-latest
    name: Minishell Tester
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
         make
         rm -rf minishell_tester
         git clone https://github.com/LucasKuhn/minishell_tester.git 
         ls -la
         cd minishell_tester
         sed -i '19d' redirects
         cp ../minishell . && ./tester
