# .github/workflows/tester.yml
name: tester
on:
  push:
    branches:
      - refactor
  pull_request:
    branches:
      - main

jobs:
  norminette_v3_job:
    runs-on: ubuntu-latest
    name: norminette v3
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3

  minishell_tester_job:
    runs-on: ubuntu-latest
    name: Minishell Tester
    timeout-seconds: 30 
    steps:
      - uses: actions/checkout@v2
      - name: Clone minishell tester and run tests
        run: |
          chmod +x execute.sh
          ./execute.sh